config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'cocktails#index'

  # get 'cocktails', to: "cocktails#index", as: "cocktails"
  get 'cocktails/:id', to: "cocktails#show", as: "cocktail", constraints: {id: /\d+/}

  get 'categories', to: "categories#index", as: "categories"
  get 'categories/:id', to: "categories#show", as: "category", constraints: {id: /\d+/}

  post 'cocktails/edit_quantity/:id', to: 'cocktails#edit_quantity', as: "edit_quantity"
  post 'cocktails/add_to_cart/:id', to: 'cocktails#add_to_cart', as: "add_to_cart"
  delete 'cocktails/remove_from_cart/:id', to: 'cocktails#remove_from_cart', as: "remove_from_cart"

  get "checkout", to: "checkouts#show"
  get "success", to: "checkouts#success", as: "success"
  get "cancel", to: "checkouts#cancel", as: "cancel"

  get 'orders_history', to: "user_profile#order_history"
  get 'orders_history/:id', to: "user_profile#show", as: "order", constraints: {id: /\d+/}

  resources :cocktails, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  devise_for :admin_users, ActiveAdmin: :Devise
  ActiveAdmin.routes(self)
  resources :cocktails
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  belongs_to :category
  has_many :cocktail_ingredient
  has_many :ingredients, through: :cocktail_ingredient
  has_many :order_items

  validates :cocktail_name, :price, :category, presence: true
  validates :price, numericality: true
  validates :cocktail_name, uniqueness: true
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :initialize_session
  before_action :load_cart

  def index
    @cocktails = Cocktail.includes(:category).order(cocktail_name: :asc).page(params[:page])
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @ingredients = Ingredient.all.order(ingredient_name: :asc)
  end

  def search
    keyword_search = "%#{params[:keywords]}%"
    category_selected = "%#{params["category"]}%"
    
    if "%#{params["category"]}%"
      @cocktails = Cocktail.where("cocktail_name LIKE ? AND category_id LIKE ?", keyword_search, category_selected).order(cocktail_name: :asc)
      @ingredients = Ingredient.where("ingredient_name LIKE ? ", keyword_search).order(ingredient_name: :asc)
    elsif
      @cocktails = Cocktail.where("cocktail_name LIKE ? ", keyword_search).order(cocktail_name: :asc)
      @ingredients = Ingredient.where("ingredient_name LIKE ? ", keyword_search).order(ingredient_name: :asc)
    end
  end

  def add_to_cart
    id = params[:id].to_i

    session[:cart] << id unless session[:cart].include?(id)
    session[:quantity].append(1)
    redirect_to root_path
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/index.html.erb
<h1> All Cocktails</h1>

<ul>
    <% @cocktails.each do |c| %>
        <li><%= link_to c.cocktail_name, cocktail_path(c) %></li>
    <% end %>
</ul>

<%= page_entries_info @cocktails %>
<%= paginate @cocktails %>

app/views/cocktails/search.html.erb
<h1>All result for "<%= params[:keywords] %>"</h1>

<% if @cocktails.count == 0%>
    <p>No result for <%= params[:keywords] %><p>
<% end %>

<ul>
    <% @cocktails.each do |c| %>
        <li><%= link_to c.cocktail_name, c %></li>
    <% end %>
    <% if params["category"] == ""%>
        <% @ingredients.each do |i| %>
            <li><%= i.ingredient_name %></li>
        <% end %>
    <% end %>
</ul>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.cocktail_name %></h1>

<h2>Category: <%= @cocktail.category.category_name %></h2>

<h2>All ingredients:</h2>
<ul>
    <% @cocktail.ingredients.each do |i| %>
        <li><%=i.ingredient_name%></li>
    <% end %>
</ul>

<h2>Instruction:</h2>
<p><%= @cocktail.instruction %></p>

<h2>Image:</h2>
<img src=<%= @cocktail.image %> alt="cocktail" height=200>

<h2>Price: <%=number_to_currency @cocktail.price / 100.0 %></h2>
<p><%= button_to 'Add to cart', add_to_cart_path(@cocktail.id), method: :post%></p>