config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'cocktails#index'

  # get 'cocktails', to: "cocktails#index", as: "cocktails"
  get 'cocktails/:id', to: "cocktails#show", as: "cocktail", constraints: {id: /\d+/}

  get 'categories', to: "categories#index", as: "categories"
  get 'categories/:id', to: "categories#show", as: "category", constraints: {id: /\d+/}

  post 'cocktails/edit_quantity/:id', to: 'cocktails#edit_quantity', as: "edit_quantity"
  post 'cocktails/add_to_cart/:id', to: 'cocktails#add_to_cart', as: "add_to_cart"
  delete 'cocktails/remove_from_cart/:id', to: 'cocktails#remove_from_cart', as: "remove_from_cart"

  get "checkout", to: "checkouts#show"
  get "success", to: "checkouts#success", as: "success"
  get "cancel", to: "checkouts#cancel", as: "cancel"

  get 'orders_history', to: "user_profile#order_history"
  get 'orders_history/:id', to: "user_profile#show", as: "order", constraints: {id: /\d+/}

  resources :cocktails, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  devise_for :admin_users, ActiveAdmin: :Devise
  ActiveAdmin.routes(self)
  resources :cocktails
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :cocktails

    validates :category_name, presence: true

    def to_s
        category_name
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @categories = Category.order(category_name: :asc)
  end

  def show
    @category = Category.find(params[:id])
    @cocktails = Cocktail.all.order(cocktail_name: :asc)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>All Categories</h1>
<ul>
    <% @categories.each do |c| %>
        <li><%= link_to c.category_name , category_path(c) %></li>
    <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.category_name %></h1>

<ul>
    <% @cocktails.each do |c| %>
        <% if c.category.category_name == @category.category_name %>
            <li><%= link_to c.cocktail_name, cocktail_path(c) %></li>
        <% end %>
    <% end %>
</ul>