config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'cocktails#index'

  # get 'cocktails', to: "cocktails#index", as: "cocktails"
  get 'cocktails/:id', to: "cocktails#show", as: "cocktail", constraints: {id: /\d+/}

  get 'categories', to: "categories#index", as: "categories"
  get 'categories/:id', to: "categories#show", as: "category", constraints: {id: /\d+/}

  post 'cocktails/edit_quantity/:id', to: 'cocktails#edit_quantity', as: "edit_quantity"
  post 'cocktails/add_to_cart/:id', to: 'cocktails#add_to_cart', as: "add_to_cart"
  delete 'cocktails/remove_from_cart/:id', to: 'cocktails#remove_from_cart', as: "remove_from_cart"

  get "checkout", to: "checkouts#show"
  get "success", to: "checkouts#success", as: "success"
  get "cancel", to: "checkouts#cancel", as: "cancel"

  get 'orders_history', to: "user_profile#order_history"
  get 'orders_history/:id', to: "user_profile#show", as: "order", constraints: {id: /\d+/}

  resources :cocktails, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  devise_for :admin_users, ActiveAdmin: :Devise
  ActiveAdmin.routes(self)
  resources :cocktails
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  def order_history
    @orders = Order.where("user_id LIKE ?", current_user.id).order(created_at: :desc)
  end

  def show
    @order= Order.find(params[:id])
    @order_items = OrderItem.where("order_id LIKE ? ", params[:id])
    order_province = @order.province.to_s
    province = Province.find_by(code: order_province)
    @tax_rate = province.pst + province.pst + province.hst
  end
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/user_profile/order_history.html.erb
<h1>Order History</h1>
<table>
    <tr>
        <th>Order Number</th>
        <th>Date</th>
        <th>Total</th>
    </tr>
    <% @orders.each do |order| %>
    <tr>
        <td><%= link_to order.id, order_path(order) %></td>
        <td><%= order.created_at %></td>
        <td>$<%= order.total_price / 100 %></td>
    </tr>  
    <% end %>  
</table>

app/views/user_profile/show.html.erb
<h1>Order number: <%= @order.id %></h1>

<ol>
    <% @order_items.each do |item| %>
        <li><%= item.cocktail.cocktail_name %>, quantity: <%= item.quantity %></li>
    <% end %>
</ol>
<p>Tax: $<%= number_with_precision(@order.total_price * @tax_rate / 100, precision: 2) %></p>
<p>Total amount: $<%= @order.total_price / 100 %></p>