config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'cocktails#index'

  # get 'cocktails', to: "cocktails#index", as: "cocktails"
  get 'cocktails/:id', to: "cocktails#show", as: "cocktail", constraints: {id: /\d+/}

  get 'categories', to: "categories#index", as: "categories"
  get 'categories/:id', to: "categories#show", as: "category", constraints: {id: /\d+/}

  post 'cocktails/edit_quantity/:id', to: 'cocktails#edit_quantity', as: "edit_quantity"
  post 'cocktails/add_to_cart/:id', to: 'cocktails#add_to_cart', as: "add_to_cart"
  delete 'cocktails/remove_from_cart/:id', to: 'cocktails#remove_from_cart', as: "remove_from_cart"

  get "checkout", to: "checkouts#show"
  get "success", to: "checkouts#success", as: "success"
  get "cancel", to: "checkouts#cancel", as: "cancel"

  get 'orders_history', to: "user_profile#order_history"
  get 'orders_history/:id', to: "user_profile#show", as: "order", constraints: {id: /\d+/}

  resources :cocktails, only: [:index, :show] do
    collection do
      get "search"
    end
  end

  devise_for :admin_users, ActiveAdmin: :Devise
  ActiveAdmin.routes(self)
  resources :cocktails
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cocktails

  validates :user, :total_price, :items_count, presence: true
  validates :total_price, numericality: true
  validate :items_count, numericality: { only_integer: true }
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :cocktails

    validates :category_name, presence: true

    def to_s
        category_name
    end
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  belongs_to :category
  has_many :cocktail_ingredient
  has_many :ingredients, through: :cocktail_ingredient
  has_many :order_items

  validates :cocktail_name, :price, :category, presence: true
  validates :price, numericality: true
  validates :cocktail_name, uniqueness: true
end

app/models/cocktail_ingredient.rb
class CocktailIngredient < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :cocktail_ingredient
    has_many :cocktails, through: :cocktail_ingredient

    validates :ingredient_name, presence: true
    validates :ingredient_name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  validates :user, :total_price, presence: true
  validates :total_price, numericality: true
  # validates :item_count, numericality: { only_integer: true }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :cocktail
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :initialize_session
    before_action :load_cart

    def initialize_session
        session[:cart] ||= []
        session[:quantity] ||= []
        session[:checkout_payment_id] ||= ""
        session[:new_order] ||= nil
    end

    def load_cart
        @cart = Cocktail.find(session[:cart])
    end

    def remove_from_cart
        id = params[:id].to_i
        session[:cart].delete(id)
        redirect_to root_path
    end

    def edit_quantity
        index = session[:cart].index(params[:id].to_i)
        puts index
        puts params[:quantity]
        session[:quantity][index] = params[:quantity]
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @categories = Category.order(category_name: :asc)
  end

  def show
    @category = Category.find(params[:id])
    @cocktails = Cocktail.all.order(cocktail_name: :asc)
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :initialize_session
  before_action :load_cart
  Stripe.api_key = 'sk_test_51MClOoIFgMFAypoN9JWYH4wmanfYbGJQTNeKFKEvNo1TqByg0ugKySWISQbTtZnmXpg4dDPy7GxWP8GbKKD6hUq400aCeLOaFk'

  def show   
    item_list = []

    session[:cart].each_with_index do |i, index|
      item = Cocktail.find(i)
      item_list.append(
      {       
        price_data: {
          currency: 'cad',
          unit_amount: item.price,
          product_data: {
            name: item.cocktail_name,
          },
          tax_behavior: 'exclusive',
        },
        quantity: session[:quantity][index]
      })
    end

    domain = 'http://localhost:3000/'
    checkout_session = Stripe::Checkout::Session.create({
      # line_items: [{
      #   price: 'price_1MDCa6IFgMFAypoNwvZtQPKV',
      #   quantity: 1,
      # }],
      line_items: item_list,
      mode: 'payment',
      success_url: domain + 'success',
      cancel_url: domain,
      shipping_address_collection: {allowed_countries: ['CA']},
      automatic_tax: {enabled: true},
    })

    puts "id:" + checkout_session.id

    session[:checkout_payment_id] = checkout_session.id

    puts "session:" + session[:checkout_payment_id]
    redirect_to checkout_session.url, allow_other_host: true
  end

  def success
    if !session[:cart].empty?
      checkout_session = Stripe::Checkout::Session.retrieve(
        session[:checkout_payment_id].to_s
      )

      @payment_id = checkout_session.payment_intent

      payment_intent = Stripe::PaymentIntent.retrieve(
        @payment_id
      )

      address = "#{payment_intent.shipping.address.line2} #{payment_intent.shipping.address.line1} #{payment_intent.shipping.address.city} #{payment_intent.shipping.address.state} #{payment_intent.shipping.address.postal_code}, #{payment_intent.shipping.address.country}"

      order = current_user.orders.create(
        payment: @payment_id,
        total_price: payment_intent.amount,
        address: address, 
        province: payment_intent.shipping.address.state
      )

      puts "order:" + order.to_s

      session[:cart].each_with_index do |i, index|
        order.order_items.create(
          cocktail: Cocktail.find(i),
          price: Cocktail.find(i).price,
          quantity: session[:quantity][index],
        )
      end

      current_user.update(address: address)

      session[:new_order] = order.id
      session[:cart] = []
      session[:quantity] = []
    end

    @total_amount = Order.find(session[:new_order].to_i).total_price / 100.0
    @order_items = OrderItem.where("order_id LIKE ? ", session[:new_order].to_i)
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :initialize_session
  before_action :load_cart

  def index
    @cocktails = Cocktail.includes(:category).order(cocktail_name: :asc).page(params[:page])
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @ingredients = Ingredient.all.order(ingredient_name: :asc)
  end

  def search
    keyword_search = "%#{params[:keywords]}%"
    category_selected = "%#{params["category"]}%"
    
    if "%#{params["category"]}%"
      @cocktails = Cocktail.where("cocktail_name LIKE ? AND category_id LIKE ?", keyword_search, category_selected).order(cocktail_name: :asc)
      @ingredients = Ingredient.where("ingredient_name LIKE ? ", keyword_search).order(ingredient_name: :asc)
    elsif
      @cocktails = Cocktail.where("cocktail_name LIKE ? ", keyword_search).order(cocktail_name: :asc)
      @ingredients = Ingredient.where("ingredient_name LIKE ? ", keyword_search).order(ingredient_name: :asc)
    end
  end

  def add_to_cart
    id = params[:id].to_i

    session[:cart] << id unless session[:cart].include?(id)
    session[:quantity].append(1)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/layouts/_cart.html.erb
<details>
    <summary>Cart</summary>
    <ul>
        <% if @cart.empty? %>
            <p>No items in cart</p>
        <%else%>
            <%count = 0 %>
            <% @cart.each do |item| %>
                <li><%= item.cocktail_name%>, quantity:
                <%= form_tag edit_quantity_path(item) do %> 
                    <%= number_field_tag(:quantity, nil, class: "input", value: session[:quantity][count])%>
                <% end %> 
                <p><%= button_to 'Remove from cart', remove_from_cart_path(item), method: :delete%></p>
                </li>
                <%count += 1%>
            <% end %>
            <p><%= button_to 'Checkout', checkout_path, data: {turbo: false}, method: :get%></p>
        <%end%>
    </ul>
</details>

app/views/layouts/_navbar.html.erb
<header>
    <div class='container'>
        <nav>
            <ul>
                <li><%= link_to "Cocktails", cocktails_path%></li>
                <li><%= link_to "Categories", categories_path%></li>
                <li><%= link_to "Orders", orders_history_path%></li>
            </ul>
        </nav>
        <p class="navbar-text float-right">
            <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, :class => 'navbar-link'  %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
        </p>
    </div>
</header>        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CocktailsStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/cart" %>
    <%= form_with(url: search_cocktails_path, method: :get, local: true) do %>
      <div class="field is-ground mb-5" style="text-align:left">
        <div class="control is-expanded" style="display:inline">
          <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For Cocktails') %>
          <%= select_tag 'category', options_for_select(Category.all.map{|el| [el.category_name, el.id]}), :prompt => "All Categories" %>
        </div>
        <div class="control" style="display:inline">
          <%=submit_tag("Search", class: "button is-primary")%>
        </div>
      </div>
    <% end %> 
    <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>